import type { CompositionDefinition } from "./types";

const core = [
  { field: "businessName", message: "Add the business name." },
  { field: "mainService", message: "Describe the main service." },
  { field: "audience", message: "Describe the ideal customer." },
  { field: "goal", message: "Choose the website's main action." },
  { field: "bookingLink", message: "Add a real booking or contact destination." },
] as const;

export const compositions: CompositionDefinition[] = [
  {
    id: "guided-personal",
    name: "Guided personal",
    description: "Warm, high-trust storytelling for a person-led coaching business.",
    visitorJob: "Decide whether this coach understands me and take a comfortable first step.",
    visualGrammar: "Warm editorial rhythm, human introduction, guided steps and one calm action.",
    preferredFor: [/personal trainer/i, /coach/i, /prenatal/i, /older/i, /rehab/i, /wellness/i],
    supportedRoutes: ["book", "apply", "credibility"],
    supportedAssets: ["image-light", "image-led", "image-rich"],
    required: [...core],
    recommendedFields: ["differentiator", "process", "credentials", "testimonialQuote"],
  },
  {
    id: "editorial-studio",
    name: "Editorial studio",
    description: "Quiet, spacious and image-aware for movement and wellbeing studios.",
    visitorJob: "Understand the atmosphere, classes and easiest way to visit.",
    visualGrammar: "Editorial type, generous space, tactile colour and alternating image moments.",
    preferredFor: [/pilates/i, /yoga/i, /barre/i, /movement/i, /studio/i],
    supportedRoutes: ["book", "class", "credibility"],
    supportedAssets: ["image-light", "image-led", "image-rich"],
    required: [...core],
    recommendedFields: ["schedule", "prices", "testimonialQuote", "location"],
  },
  {
    id: "digital-momentum",
    name: "Digital momentum",
    description: "A crisp product-led journey for online coaching and programmes.",
    visitorJob: "See how the programme works and decide whether to apply or join.",
    visualGrammar: "Structured programme map, interface-like panels and strong informational hierarchy.",
    preferredFor: [/online/i, /remote/i, /programme/i, /nutrition/i],
    supportedRoutes: ["apply", "purchase", "waitlist"],
    supportedAssets: ["image-light", "image-led"],
    required: [...core],
    recommendedFields: ["process", "prices", "results", "faqQuestion"],
  },
  {
    id: "documentary-performance",
    name: "Documentary performance",
    description: "Direct, photographic and credible for serious training environments.",
    visitorJob: "Judge the coaching standard and book the right performance service.",
    visualGrammar: "Documentary photography, restrained colour, performance detail and proof-led modules.",
    preferredFor: [/strength/i, /performance/i, /boxing/i, /martial/i, /conditioning/i],
    supportedRoutes: ["book", "apply", "credibility"],
    supportedAssets: ["image-led", "image-rich"],
    required: [...core, { minimumAssets: 1, message: "Add one usable coach, client or venue photograph." }],
    recommendedFields: ["credentials", "results", "process"],
  },
  {
    id: "precision-practice",
    name: "Precision practice",
    description: "Measured and reassuring for specialist or evidence-led services.",
    visitorJob: "Understand the assessment method and verify professional credibility.",
    visualGrammar: "Clinical clarity, measured diagrams, precise spacing and sourced proof.",
    preferredFor: [/physio/i, /rehab/i, /clinical/i, /specialist/i, /sports therapy/i],
    supportedRoutes: ["book", "credibility"],
    supportedAssets: ["image-light", "image-led"],
    required: [...core, { field: "credentials", message: "Add the professional credentials that may be displayed." }],
    recommendedFields: ["results", "process", "faqQuestion"],
  },
  {
    id: "community-schedule",
    name: "Community schedule",
    description: "Schedule-first and welcoming for class-led businesses.",
    visitorJob: "Find the right session quickly and know how to join.",
    visualGrammar: "Visible timetable, community cues, practical cards and repeated joining actions.",
    preferredFor: [/group/i, /bootcamp/i, /club/i, /community/i, /studio/i, /gym/i],
    supportedRoutes: ["class", "book"],
    supportedAssets: ["image-light", "image-led", "image-rich"],
    required: [...core, { field: "schedule", message: "Add the real class or session schedule." }],
    recommendedFields: ["prices", "testimonialQuote", "location"],
  },
  {
    id: "private-catalogue",
    name: "Private catalogue",
    description: "Quiet luxury for premium private training and wellness.",
    visitorJob: "Compare a small number of premium services and make a private enquiry.",
    visualGrammar: "Typographic restraint, service catalogue, discreet proof and premium whitespace.",
    preferredFor: [/private/i, /premium/i, /luxury/i, /executive/i, /concierge/i, /wellness/i],
    supportedRoutes: ["book", "apply", "credibility"],
    supportedAssets: ["image-light", "image-led"],
    required: [...core, { field: "offer", message: "Describe the premium service or first invitation." }],
    recommendedFields: ["prices", "credentials", "differentiator"],
  },
  {
    id: "campaign-launch",
    name: "Campaign launch",
    description: "Focused conversion page for a defined programme, intake or event.",
    visitorJob: "Understand the offer, timing and next step without distraction.",
    visualGrammar: "Single-offer narrative, programme breakdown, deadline context and repeated action.",
    preferredFor: [/challenge/i, /programme/i, /course/i, /intake/i, /event/i],
    supportedRoutes: ["purchase", "waitlist", "apply"],
    supportedAssets: ["image-light", "image-led"],
    required: [...core, { field: "offer", message: "Name the programme or campaign." }],
    recommendedFields: ["programmeStart", "programmeCapacity", "prices", "faqQuestion"],
  },
];

