const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");

export const clerkAppearance = {
  cssLayerName: "clerk",
  options: {
    logoPlacement: "inside" as const,
    logoLinkUrl: basePath || "/",
    logoImageUrl: typeof window !== "undefined" ? `${window.location.origin}${basePath}/logo.svg` : "/logo.svg",
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
  },
  variables: {
    colorPrimary: "#ed633b",
    colorForeground: "#202736",
    colorMutedForeground: "#697080",
    colorDanger: "#c8483d",
    colorBackground: "#fbfaf5",
    colorInput: "#fbfaf5",
    colorInputForeground: "#202736",
    colorNeutral: "#202736",
    colorModalBackdrop: "rgba(32,39,54,0.55)",
    fontFamily: "'DM Sans', ui-sans-serif, system-ui, sans-serif",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full flex items-center justify-center",
    cardBox: "bg-[#fbfaf5] border border-[#dedbd2] shadow-[0_30px_80px_-30px_rgba(32,39,54,0.25)] rounded-2xl w-[440px] max-w-full overflow-hidden mx-auto",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none px-2",
    footer: "!shadow-none !border-0 !bg-[#f1eee6] !rounded-none border-t border-[#dedbd2]",
    headerTitle: "font-serif text-2xl text-[#202736] tracking-tight",
    headerSubtitle: "text-sm text-[#697080]",
    socialButtonsBlockButton: "border border-[#dedbd2] hover:bg-[#f1eee6] text-[#202736] rounded-lg",
    socialButtonsBlockButtonText: "text-sm font-medium text-[#202736]",
    formFieldLabel: "text-xs font-medium text-[#4d5668] uppercase tracking-wide",
    footerActionLink: "text-[#ed633b] font-medium hover:underline",
    footerActionText: "text-sm text-[#697080]",
    dividerText: "text-[#8b92a0] text-xs uppercase tracking-widest",
    dividerLine: "bg-[#dedbd2]",
    identityPreviewEditButton: "text-[#ed633b] hover:underline",
    formFieldSuccessText: "text-[#2a7c62] text-sm",
    alertText: "text-[#202736] text-sm",
    logoBox: "flex items-center justify-center mb-2",
    logoImage: "h-9 w-auto",
    formButtonPrimary: "bg-[#ed633b] hover:bg-[#d95431] text-white font-medium rounded-lg shadow-none normal-case tracking-normal",
    formFieldInput: "border border-[#dedbd2] bg-[#fbfaf5] text-[#202736] rounded-lg focus:border-[#ed633b] focus:ring-0",
    footerAction: "hidden",
    alert: "border border-[#dedbd2] bg-[#f1eee6] text-[#202736]",
    otpCodeFieldInput: "border border-[#dedbd2] bg-[#fbfaf5] text-[#202736] rounded-lg",
    formFieldRow: "gap-1",
    main: "gap-4",
    userPreviewMainIdentifier: "text-[#202736]",
  },
};