import type { CSSProperties, ReactNode } from "react";
import type { SitePlanV1 } from "@workspace/site-plan";

type Copy = { headline: string; subheadline: string; about: string; button: string };
type Section = { id: string; eyebrow?: string; title: string; body: string; highlights?: string[] };
type Brief = {
  businessName: string; mainService: string; audience: string; location: string; deliveryMode?: string;
  offer: string; credentials: string; results: string; testimonialQuote: string; testimonialName: string;
  process: string; faqQuestion: string; faqAnswer: string; schedule?: string; serviceDetails?: string;
  sections?: string[];
};
type Part = "headline" | "subheadline" | "about" | "button";
export type DigitalMomentumProps = {
  compositionId: string; brief: Brief; copy: Copy; sections: Section[]; heroImage: string; useImage: boolean;
  accent: string; narrow: boolean; editable?: boolean; selectedPart?: string; onSelect?: (part: Part) => void;
  onReplaceImage?: () => void; sitePlan?: SitePlanV1; fontStyle?: string; paletteDark?: string; paletteLight?: string;
  previewMode?: "desktop" | "tablet" | "mobile";
};

const cn = (...values: Array<string | false | null | undefined>) => values.filter(Boolean).join(" ");
const splitItems = (value = "") => value.split(/\n|;|\u2022/).map((item) => item.trim()).filter(Boolean).slice(0, 5);
const sectionOf = (sections: Section[], id: string) => sections.find((item) => item.id === id);
const cleanQuote = (value: string) => value.trim().replace(/^[“"']+|[”"']+$/g, "");
const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" })[char] || char);

function resolveDigitalMomentum(props: DigitalMomentumProps) {
  const byId = Object.fromEntries(["services", "approach", "about", "results", "testimonial", "faq", "contact"].map((id) => [id, sectionOf(props.sections, id)])) as Record<string, Section | undefined>;
  const schedule = splitItems(props.brief.schedule);
  const selected = new Set(props.brief.sections || []);
  const available = [
    byId.services && selected.has("services") ? "services" : "",
    byId.approach && selected.has("approach") ? "approach" : "",
    schedule.length && selected.has("schedule") ? "schedule" : "",
    byId.about && selected.has("about") ? "about" : "",
    (byId.results || props.brief.credentials || props.brief.results) && selected.has("results") ? "results" : "",
    (byId.testimonial || props.brief.testimonialQuote) && selected.has("testimonial") ? "testimonial" : "",
    (byId.faq || (props.brief.faqQuestion && props.brief.faqAnswer)) && selected.has("faq") ? "faq" : "",
    selected.has("contact") ? "contact" : "",
  ].filter(Boolean);
  const ordered = [...new Set([...(props.sitePlan?.narrative.orderedModuleIds || []), ...available])].filter((id) => available.includes(id));
  const contactIndex = ordered.indexOf("contact");
  if (contactIndex >= 0) ordered.push(...ordered.splice(contactIndex, 1));
  const images = props.useImage ? [...new Set([props.heroImage, ...(props.sitePlan?.assets?.images.map((asset) => asset.url) || [])].filter(Boolean))] : [];
  const requestedHero = props.sitePlan?.hero.variant || (images.length ? "image-signal" : "track");
  const heroVariant = requestedHero === "image-signal" && !images.length ? "track" : ["track", "dashboard", "image-signal"].includes(requestedHero) ? requestedHero : images.length ? "image-signal" : "track";
  const headlineFit = props.sitePlan?.responsive.headlineFit || (props.copy.headline.length > 72 ? "compact" : props.copy.headline.length > 42 ? "balanced" : "display");
  const displayFont = props.fontStyle === "Premium editorial" ? 'Georgia,"Times New Roman",serif' : props.fontStyle === "Clean professional" ? '"Trebuchet MS",Arial,sans-serif' : '"Arial Black",Arial,sans-serif';
  const ink = props.paletteDark || "#121625";
  const paper = props.paletteLight || "#f7f8f4";
  const primary = props.accent || "#283cf4";
  const acid = "#ddff53";
  const steps = byId.approach?.highlights?.length ? byId.approach.highlights : splitItems(props.brief.process);
  const serviceItems = byId.services?.highlights?.length ? byId.services.highlights : [props.brief.serviceDetails || byId.services?.body || props.brief.offer].filter(Boolean);
  const proof = [...new Set([byId.results?.body, props.brief.credentials, props.brief.results].filter((item): item is string => Boolean(item)))];
  return { byId, schedule, ordered, images, heroVariant, headlineFit, displayFont, ink, paper, primary, acid, steps, serviceItems, proof };
}

function Editable({ part, props, className, children }: { part: Part; props: DigitalMomentumProps; className?: string; children: ReactNode }) {
  return <button disabled={!props.editable} onClick={() => props.onSelect?.(part)} className={cn("block text-left", className, props.editable && "rounded-sm outline-none hover:ring-2 hover:ring-white/50", props.editable && props.selectedPart === part && "ring-2 ring-white")}>{children}</button>;
}

function TrackArt({ acid }: { acid: string }) {
  return <div aria-hidden="true" className="absolute right-[-18%] top-[-22%] h-[720px] w-[720px] rotate-[-18deg] opacity-45"><svg viewBox="0 0 740 740" className="h-full w-full fill-none stroke-white/60"><circle cx="370" cy="370" r="300" /><circle cx="370" cy="370" r="245" /><circle cx="370" cy="370" r="190" /><circle cx="370" cy="370" r="135" /><path d="M490 96 Q670 190 670 370" /></svg><span className="absolute left-[26%] top-[20%] h-6 w-6 rounded-full" style={{ background: acid }} /></div>;
}

export function DigitalMomentumSite(props: DigitalMomentumProps) {
  const resolved = resolveDigitalMomentum(props);
  const { byId, schedule, ordered, images, heroVariant, headlineFit, displayFont, ink, paper, primary, acid, steps, serviceItems, proof } = resolved;
  const compact = props.previewMode === "tablet" || props.previewMode === "mobile";
  const mobile = props.previewMode === "mobile" || props.narrow;
  const vars = { "--dm-ink": ink, "--dm-paper": paper, "--dm-primary": primary, "--dm-acid": acid, "--dm-display": displayFont } as CSSProperties;
  const titleSize = mobile ? headlineFit === "compact" ? "text-[3.1rem]" : "text-[4.2rem]" : heroVariant === "dashboard" ? headlineFit === "compact" ? "text-[4.7rem]" : "text-[6.4rem]" : headlineFit === "compact" ? "text-[5.5rem]" : headlineFit === "balanced" ? "text-[7rem]" : "text-[9rem]";
  const heading = cn("dm-display font-black uppercase leading-[.87] tracking-[-.075em]", mobile ? "text-[3.3rem]" : compact ? "text-[4.5rem]" : "text-[6.5rem]");
  const action = <Editable part="button" props={props} className="inline-flex items-center gap-6 rounded-full px-6 py-4 text-[10px] font-black uppercase tracking-[.08em]" ><span>{props.copy.button}</span><span>↗</span></Editable>;
  const sectionPad = mobile ? "px-6 py-16" : "px-14 py-24";

  const module = (id: string, index: number) => {
    const number = String(index + 1).padStart(2, "0");
    if (id === "services" && byId.services) return <section key={id} data-module="services" className={sectionPad} style={{ background: paper, color: ink }}><div className="flex justify-between border-t border-current pt-3 text-[9px] font-black uppercase tracking-[.16em]"><span>{byId.services.eyebrow || "The programme"}</span><span>{number} / Built around you</span></div><div className={cn("grid items-end gap-12 py-16", compact ? "grid-cols-1" : "grid-cols-[1.2fr_.8fr]")}><h2 className={heading}>{byId.services.title}</h2><div><p className="text-xl font-bold leading-8 tracking-[-.025em]">{byId.services.body}</p></div></div>{serviceItems.length > 0 && <div className={cn("grid border-t border-black/20", compact ? "grid-cols-1" : "grid-cols-3")}>{serviceItems.slice(0, 3).map((item, itemIndex) => <article key={item} className="min-h-52 border-b border-black/20 p-6 md:border-b-0 md:border-r"><span className="text-xs font-black" style={{ color: primary }}>0{itemIndex + 1}</span><strong className="mt-14 block text-2xl tracking-[-.04em]">{item}</strong></article>)}</div>}</section>;
    if (id === "schedule") return <section key={id} data-module="schedule" className={sectionPad} style={{ background: `color-mix(in srgb, ${paper} 82%, ${primary})`, color: ink }}><div className="flex justify-between border-t border-current pt-3 text-[9px] font-black uppercase tracking-[.16em]"><span>Inside the experience</span><span>{number} / Your week</span></div><div className={cn("mt-14 grid border border-black/25 bg-white/60 shadow-[18px_18px_0_rgba(40,60,244,.16)]", compact ? "grid-cols-1" : "grid-cols-[.36fr_.64fr]")}><div className="border-b border-black/20 p-7 md:border-b-0 md:border-r"><span className="text-[9px] font-black uppercase tracking-[.15em]">Your training</span><h2 className="dm-display mt-4 text-4xl font-black uppercase leading-none tracking-[-.06em]">Week overview</h2><p className="mt-5 text-sm leading-6 opacity-65">The supplied schedule, organised into one clear view.</p></div><div className="p-7"><div className="text-[9px] font-black uppercase tracking-[.15em]" style={{ color: primary }}>Scheduled sessions</div><div className="mt-6 divide-y divide-black/20 border-y border-black/20">{schedule.map((item, itemIndex) => <div key={item} className="grid grid-cols-[44px_1fr] py-5"><span className="text-xs opacity-45">0{itemIndex + 1}</span><strong>{item}</strong></div>)}</div></div></div></section>;
    if (id === "approach" && byId.approach) return <section key={id} data-module="approach" className={sectionPad} style={{ background: ink, color: paper }}><div className="flex justify-between border-t border-current pt-3 text-[9px] font-black uppercase tracking-[.16em]"><span>{byId.approach.eyebrow || "How coaching works"}</span><span>{number} / You are not a template</span></div><div className={cn("mt-16 grid gap-16", compact ? "grid-cols-1" : "grid-cols-2")}><div><h2 className={heading}>{byId.approach.title}</h2><p className="mt-8 max-w-xl text-base leading-7 opacity-70">{byId.approach.body}</p></div><ol className="divide-y divide-white/25 border-t border-white/25">{steps.map((item, itemIndex) => <li key={item} className="py-6"><span className="text-[9px] font-black uppercase tracking-[.16em]" style={{ color: acid }}>0{itemIndex + 1} / Your route</span><h3 className="mt-4 text-2xl font-black tracking-[-.04em]">{item}</h3></li>)}</ol></div></section>;
    if (id === "about" && byId.about) return <section key={id} data-module="about" className={sectionPad} style={{ background: `color-mix(in srgb, ${ink} 92%, ${primary})`, color: paper }}><div className="flex justify-between border-t border-current pt-3 text-[9px] font-black uppercase tracking-[.16em]"><span>{byId.about.eyebrow || "The coaching view"}</span><span>{number} / Human support</span></div><div className={cn("mt-14 grid items-center gap-14", compact ? "grid-cols-1" : "grid-cols-[.8fr_1.2fr]")}><button disabled={!props.editable || !images.length} onClick={props.onReplaceImage} className="relative aspect-square overflow-hidden rounded-full text-left" style={{ background: acid, color: primary }}>{images[1] || images[0] ? <img src={images[1] || images[0]} alt="" className="absolute inset-0 h-full w-full object-cover" /> : <span className="dm-display grid h-full place-items-center pr-3 text-[8rem] font-black tracking-[-.14em]">{(props.brief.businessName || "M").charAt(0)}↗</span>}</button><div><h2 className={heading}>{byId.about.title}</h2><Editable part="about" props={props} className="mt-8 max-w-2xl text-xl font-bold leading-8 opacity-80">{props.copy.about || byId.about.body}</Editable></div></div></section>;
    if (id === "results" && proof.length) return <section key={id} data-module="results" className={sectionPad} style={{ background: acid, color: ink }}><div className="flex justify-between border-t border-current pt-3 text-[9px] font-black uppercase tracking-[.16em]"><span>{byId.results?.eyebrow || "Evidence supplied"}</span><span>{number} / The record</span></div><div className={cn("mt-14 grid gap-8", compact ? "grid-cols-1" : "grid-cols-[.7fr_1.3fr]")}><span className="dm-display text-[8rem] font-black leading-none" style={{ color: primary }}>✳</span><div><h2 className={heading}>{byId.results?.title || "The work behind the plan."}</h2><div className="mt-10 divide-y divide-black/20 border-y border-black/20">{proof.slice(0, 3).map((item, itemIndex) => <p key={item} className="grid grid-cols-[44px_1fr] py-5 text-lg font-bold"><span className="text-xs opacity-45">0{itemIndex + 1}</span>{item}</p>)}</div></div></div></section>;
    if (id === "testimonial" && props.brief.testimonialQuote) return <section key={id} data-module="testimonial" className={sectionPad} style={{ background: paper, color: ink }}><span className="text-[9px] font-black uppercase tracking-[.16em]" style={{ color: primary }}>Client words / {number}</span><blockquote className={cn("dm-display mt-10 max-w-6xl font-black uppercase leading-[.94] tracking-[-.055em]", mobile ? "text-[2.6rem]" : "text-[4.5rem]")}>“{cleanQuote(props.brief.testimonialQuote)}”</blockquote>{props.brief.testimonialName && <cite className="mt-7 block text-[10px] not-italic uppercase tracking-[.16em] opacity-55">{props.brief.testimonialName}</cite>}</section>;
    if (id === "faq" && props.brief.faqQuestion && props.brief.faqAnswer) return <section key={id} data-module="faq" className={sectionPad} style={{ background: paper, color: ink }}><div className="flex justify-between border-t border-current pt-3 text-[9px] font-black uppercase tracking-[.16em]"><span>Quick answers</span><span>{number} / Before you begin</span></div><div className={cn("mt-14 grid gap-12", compact ? "grid-cols-1" : "grid-cols-2")}><h2 className={heading}>{byId.faq?.title || "Wondering if it fits?"}</h2><details open className="border-y border-black/20 py-6"><summary className="flex cursor-pointer list-none justify-between gap-5 text-lg font-bold"><span>{props.brief.faqQuestion}</span><span>+</span></summary><p className="mt-5 max-w-xl text-sm leading-7 opacity-65">{props.brief.faqAnswer}</p></details></div></section>;
    if (id === "contact") return <section key={id} data-module="contact" className={cn(sectionPad, "min-h-[580px]")} style={{ background: primary, color: paper }}><span className="text-[9px] font-black uppercase tracking-[.16em]">Your next step / {number}</span><h2 className={cn("dm-display mt-16 font-black uppercase leading-[.82] tracking-[-.085em]", mobile ? "text-[5rem]" : "text-[10rem]")}>{byId.contact?.title || "Ready to move?"}</h2><p className="mt-8 max-w-xl text-xl leading-8">{byId.contact?.body || props.brief.offer || props.copy.subheadline}</p><div className="mt-8 inline-block" style={{ background: acid, color: ink }}>{action}</div></section>;
    return null;
  };

  const heroGraphic = heroVariant === "image-signal" && images[0] ? <button disabled={!props.editable} onClick={props.onReplaceImage} className={cn("relative overflow-hidden", mobile ? "min-h-[360px]" : "min-h-[680px]")}><img src={images[0]} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 mix-blend-multiply" style={{ background: `${primary}88` }} /><span className="absolute bottom-6 left-6 rounded-full px-4 py-2 text-[9px] font-black uppercase tracking-[.15em]" style={{ background: acid, color: ink }}>Customer image / signal crop</span></button> : heroVariant === "dashboard" ? <div className={cn("z-20 min-h-[460px] border border-white/25 bg-white/10 p-7", mobile ? "relative mx-6 mb-8" : "absolute right-14 top-28 w-[40%]")}><span className="text-[9px] font-black uppercase tracking-[.16em]">Coaching overview</span><div className="mt-8 grid gap-3"><div className="border border-white/20 p-5"><span className="text-[9px] uppercase opacity-55">Service</span><strong className="mt-3 block text-xl">{props.brief.mainService}</strong></div><div className="border border-white/20 p-5"><span className="text-[9px] uppercase opacity-55">Built for</span><strong className="mt-3 block text-xl">{props.brief.audience}</strong></div><div className="border border-white/20 p-5"><span className="text-[9px] uppercase opacity-55">Delivered</span><strong className="mt-3 block text-xl">{props.brief.deliveryMode || "Online"}</strong></div></div></div> : <TrackArt acid={acid} />;

  return <div className="dm-preview overflow-hidden" style={{ ...vars, background: paper, color: ink, fontFamily: "Arial,Helvetica,sans-serif" }}><style>{`.dm-preview .dm-display{font-family:var(--dm-display)}.dm-preview button{font-family:inherit}`}</style><header className="flex items-center justify-between px-6 py-5 md:px-14" style={{ background: paper, color: ink }}><div className="flex items-center gap-3"><span className="dm-display grid h-11 w-11 place-items-center rounded-full text-lg font-black" style={{ background: primary, color: paper }}>{(props.brief.businessName || "M").charAt(0)}↗</span><b className="text-lg tracking-[-.05em]">{props.brief.businessName || "ONLINE COACHING"}</b></div>{!mobile && <nav className="flex gap-7 text-[9px] font-black uppercase tracking-[.12em]">{ordered.includes("services") && <span>Programme</span>}{ordered.includes("schedule") && <span>Your week</span>}{ordered.includes("approach") && <span>How it works</span>}</nav>}</header><section data-hero={heroVariant} className={cn("relative overflow-hidden", heroVariant === "image-signal" && !mobile ? "grid grid-cols-[1.05fr_.95fr]" : "min-h-[720px]")} style={{ background: primary, color: paper }}><div className={cn("relative z-10 flex min-h-[680px] flex-col justify-between", mobile ? "p-6 py-12" : "p-14")}><div className="flex justify-between text-[9px] font-black uppercase tracking-[.16em]"><span>{props.brief.mainService}</span><span>{props.brief.deliveryMode || "Online"} ↗</span></div><div className={cn("my-14", heroVariant === "dashboard" && !mobile && "max-w-[52%]")}><Editable part="headline" props={props}><h1 className={cn("dm-display max-w-6xl font-black uppercase leading-[.82] tracking-[-.09em]", titleSize)}>{props.copy.headline}</h1></Editable><div className={cn("mt-10 grid items-end gap-9", compact || heroVariant === "dashboard" ? "grid-cols-1" : "grid-cols-[1fr_auto]")}><Editable part="subheadline" props={props} className="max-w-xl text-xl leading-8">{props.copy.subheadline}</Editable><div className="w-max" style={{ background: acid, color: ink }}>{action}</div></div></div><div className="text-[9px] font-black uppercase tracking-[.16em]">01 / Make it yours</div></div>{heroVariant === "image-signal" ? heroGraphic : <div className="pointer-events-none">{heroGraphic}</div>}</section>{ordered.map(module)}<footer className="flex flex-wrap justify-between gap-5 px-6 py-10 text-[9px] font-black uppercase tracking-[.14em]" style={{ background: ink, color: paper }}><b>{props.brief.businessName}</b><span>{props.brief.deliveryMode || props.brief.location}</span><span>{props.copy.button}</span></footer></div>;
}

export function buildDigitalMomentumHtml(props: DigitalMomentumProps, bookingUrl: string, locale: string) {
  const h = escapeHtml;
  const { byId, schedule, ordered, images, heroVariant, headlineFit, displayFont, ink, paper, primary, acid, steps, serviceItems, proof } = resolveDigitalMomentum(props);
  const action = `<a class="button" href="${h(bookingUrl)}">${h(props.copy.button)} <span aria-hidden="true">↗</span></a>`;
  const label = (left: string, right: string) => `<div class="kicker"><span>${h(left)}</span><span>${h(right)}</span></div>`;
  const headingSize = headlineFit === "compact" ? "clamp(4rem,8vw,8.5rem)" : headlineFit === "balanced" ? "clamp(4.8rem,10vw,10.5rem)" : "clamp(5.4rem,12vw,12rem)";
  const track = `<div class="track" aria-hidden="true"><svg viewBox="0 0 740 740"><circle cx="370" cy="370" r="300"/><circle cx="370" cy="370" r="245"/><circle cx="370" cy="370" r="190"/><circle cx="370" cy="370" r="135"/><path d="M490 96 Q670 190 670 370"/></svg><i></i></div>`;
  const heroVisual = heroVariant === "image-signal" && images[0] ? `<figure class="hero-image"><img src="${h(images[0])}" alt="" width="1600" height="1200"><span>Customer image / signal crop</span></figure>` : heroVariant === "dashboard" ? `<aside class="hero-dashboard"><small>COACHING OVERVIEW</small><div><span>SERVICE</span><strong>${h(props.brief.mainService)}</strong></div><div><span>BUILT FOR</span><strong>${h(props.brief.audience)}</strong></div><div><span>DELIVERED</span><strong>${h(props.brief.deliveryMode || "Online")}</strong></div></aside>` : track;
  const moduleHtml = (id: string, index: number) => {
    const number = String(index + 1).padStart(2, "0");
    if (id === "services" && byId.services) return `<section class="section programme" id="programme" data-module="services">${label(byId.services.eyebrow || "The programme", `${number} / BUILT AROUND YOU`)}<div class="programme-head"><h2>${h(byId.services.title)}</h2><p>${h(byId.services.body)}</p></div>${serviceItems.length ? `<div class="benefits">${serviceItems.slice(0, 3).map((item, itemIndex) => `<article><span>0${itemIndex + 1}</span><strong>${h(item)}</strong></article>`).join("")}</div>` : ""}</section>`;
    if (id === "schedule") return `<section class="section week" id="week" data-module="schedule">${label("Inside the experience", `${number} / YOUR WEEK`)}<div class="week-shell"><div class="week-intro"><small>YOUR TRAINING</small><h2>WEEK<br>OVERVIEW</h2><p>The supplied schedule, organised into one clear view.</p></div><div class="week-list"><small>SCHEDULED SESSIONS</small>${schedule.map((item, itemIndex) => `<div><span>0${itemIndex + 1}</span><strong>${h(item)}</strong></div>`).join("")}</div></div></section>`;
    if (id === "approach" && byId.approach) return `<section class="section approach" id="approach" data-module="approach">${label(byId.approach.eyebrow || "How coaching works", `${number} / YOU ARE NOT A TEMPLATE`)}<div class="approach-grid"><div><h2>${h(byId.approach.title)}</h2><p>${h(byId.approach.body)}</p></div><ol>${steps.map((item, itemIndex) => `<li><span>0${itemIndex + 1} / YOUR ROUTE</span><h3>${h(item)}</h3></li>`).join("")}</ol></div></section>`;
    if (id === "about" && byId.about) return `<section class="section about" id="about" data-module="about">${label(byId.about.eyebrow || "The coaching view", `${number} / HUMAN SUPPORT`)}<div class="about-grid"><div class="coach-mark">${images[1] || images[0] ? `<img src="${h(images[1] || images[0])}" alt="" width="900" height="900">` : `${h((props.brief.businessName || "M").charAt(0))}↗`}</div><div><h2>${h(byId.about.title)}</h2><p>${h(props.copy.about || byId.about.body)}</p></div></div></section>`;
    if (id === "results" && proof.length) return `<section class="section results" id="results" data-module="results">${label(byId.results?.eyebrow || "Evidence supplied", `${number} / THE RECORD`)}<div class="results-grid"><span class="star">✳</span><div><h2>${h(byId.results?.title || "The work behind the plan.")}</h2><div class="proof">${proof.slice(0, 3).map((item, itemIndex) => `<p><span>0${itemIndex + 1}</span>${h(item)}</p>`).join("")}</div></div></div></section>`;
    if (id === "testimonial" && props.brief.testimonialQuote) return `<section class="section quote" data-module="testimonial"><small>CLIENT WORDS / ${number}</small><blockquote>“${h(cleanQuote(props.brief.testimonialQuote))}”</blockquote>${props.brief.testimonialName ? `<cite>${h(props.brief.testimonialName)}</cite>` : ""}</section>`;
    if (id === "faq" && props.brief.faqQuestion && props.brief.faqAnswer) return `<section class="section questions" id="questions" data-module="faq">${label("Quick answers", `${number} / BEFORE YOU BEGIN`)}<div class="questions-grid"><h2>${h(byId.faq?.title || "Wondering if it fits?")}</h2><details open><summary>${h(props.brief.faqQuestion)}<span>+</span></summary><p>${h(props.brief.faqAnswer)}</p></details></div></section>`;
    if (id === "contact") return `<section class="section final" id="contact" data-module="contact"><small>YOUR NEXT STEP / ${number}</small><h2>${h(byId.contact?.title || "Ready to move?")}</h2><p>${h(byId.contact?.body || props.brief.offer || props.copy.subheadline)}</p>${action}</section>`;
    return "";
  };
  const schema = JSON.stringify({ "@context": "https://schema.org", "@type": "ProfessionalService", name: props.brief.businessName, description: props.copy.subheadline, areaServed: props.brief.location || undefined, url: bookingUrl.startsWith("http") ? bookingUrl : undefined }).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="${h(locale)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(props.brief.businessName)} | ${h(props.brief.mainService)}</title><meta name="description" content="${h(props.copy.subheadline)}"><meta name="theme-color" content="${h(primary)}"><script type="application/ld+json">${schema}</script><style>
:root{--ink:${ink};--paper:${paper};--primary:${primary};--acid:${acid};--display:${displayFont};--gutter:clamp(1.5rem,6vw,6.8rem)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,Helvetica,sans-serif;overflow-x:hidden}a{color:inherit}a:focus-visible,summary:focus-visible{outline:3px solid var(--acid);outline-offset:4px}h1,h2,h3,p{margin-top:0}h1,h2,h3,blockquote{font-family:var(--display);font-weight:900;text-transform:uppercase}
header{display:flex;align-items:center;justify-content:space-between;padding:1.2rem var(--gutter);background:var(--paper)}.brand{display:flex;align-items:center;gap:.75rem;font-weight:900;letter-spacing:-.04em}.mark{display:grid;width:2.8rem;height:2.8rem;place-items:center;border-radius:50%;background:var(--primary);color:var(--paper)}nav{display:flex;gap:1.75rem;font-size:.6rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}nav a{text-decoration:none}
.hero{position:relative;min-height:45rem;overflow:hidden;background:var(--primary);color:var(--paper)}.hero.variant-image-signal{display:grid;grid-template-columns:1.05fr .95fr}.hero-copy{position:relative;z-index:2;display:flex;min-height:42.5rem;flex-direction:column;justify-content:space-between;padding:3.5rem var(--gutter)}.hero-top,.kicker{display:flex;justify-content:space-between;gap:1rem;font-size:.58rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.hero h1{max-width:74rem;margin:3.5rem 0 0;font-size:${headingSize};line-height:.82;letter-spacing:-.09em}.hero-lower{display:grid;grid-template-columns:1fr auto;align-items:end;gap:2rem;margin-top:2.5rem}.hero-lower p{max-width:38rem;font-size:1.25rem;line-height:1.55}.button{display:inline-flex;width:max-content;gap:1.5rem;margin-top:1.5rem;padding:1rem 1.5rem;border-radius:3rem;background:var(--acid);color:var(--ink);font-size:.68rem;font-weight:900;letter-spacing:.08em;text-decoration:none;text-transform:uppercase}
.track{position:absolute;right:-12rem;top:-10rem;width:48rem;height:48rem;transform:rotate(-18deg);opacity:.45}.track svg{width:100%;height:100%;fill:none;stroke:#fff;stroke-width:1}.track i{position:absolute;left:26%;top:20%;width:1.5rem;height:1.5rem;border-radius:50%;background:var(--acid)}.hero-image{position:relative;min-height:42.5rem;margin:0;overflow:hidden}.hero-image:after{content:"";position:absolute;inset:0;background:color-mix(in srgb,var(--primary),transparent 48%);mix-blend-mode:multiply}.hero-image img,.coach-mark img{width:100%;height:100%;object-fit:cover}.hero-image span{position:absolute;z-index:2;bottom:1.5rem;left:1.5rem;padding:.65rem 1rem;border-radius:2rem;background:var(--acid);color:var(--ink);font-size:.56rem;font-weight:900;letter-spacing:.14em;text-transform:uppercase}
.hero-dashboard{position:absolute;right:var(--gutter);top:7rem;width:min(34rem,40vw);padding:1.75rem;border:1px solid #ffffff44;background:#ffffff12}.hero-dashboard small,.hero-dashboard span,.week small,.quote small,.final small{font-size:.58rem;font-weight:900;letter-spacing:.16em}.hero-dashboard div{margin-top:.8rem;padding:1.25rem;border:1px solid #ffffff33}.hero-dashboard span,.hero-dashboard strong{display:block}.hero-dashboard strong{margin-top:.75rem;font-size:1.2rem}.hero.variant-dashboard h1{max-width:52%;font-size:clamp(4rem,7vw,7rem)}.hero.variant-dashboard .hero-lower{max-width:52%;grid-template-columns:1fr}
.section{padding:6rem var(--gutter)}.kicker{padding-top:.75rem;border-top:1px solid currentColor}.programme-head{display:grid;grid-template-columns:1.2fr .8fr;align-items:end;gap:6vw;padding:5rem 0}.section h2{margin:0;font-size:clamp(4rem,8vw,8rem);line-height:.87;letter-spacing:-.075em}.programme-head p{font-size:1.25rem;font-weight:700;line-height:1.6}.benefits{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #0003}.benefits article{min-height:13rem;padding:1.5rem;border-right:1px solid #0003}.benefits article span{font-size:.7rem;font-weight:900;color:var(--primary)}.benefits strong{display:block;margin-top:3.5rem;font-size:1.4rem;letter-spacing:-.04em}
.week{background:color-mix(in srgb,var(--paper) 82%,var(--primary))}.week-shell{display:grid;grid-template-columns:.36fr .64fr;margin-top:3.5rem;border:1px solid #0004;background:#ffffff99;box-shadow:18px 18px 0 color-mix(in srgb,var(--primary),transparent 82%)}.week-intro{padding:2rem;border-right:1px solid #0003}.week-intro h2{margin-top:1.2rem;font-size:3.5rem}.week-intro p{margin-top:1.5rem;line-height:1.7;opacity:.65}.week-list{padding:2rem}.week-list>div{display:grid;grid-template-columns:3rem 1fr;padding:1.25rem 0;border-bottom:1px solid #0003}.week-list>div:first-of-type{margin-top:1.5rem;border-top:1px solid #0003}.week-list span{font-size:.7rem;opacity:.45}
.approach,.about{background:var(--ink);color:var(--paper)}.approach-grid,.about-grid,.results-grid,.questions-grid{display:grid;grid-template-columns:1fr 1fr;gap:7vw;margin-top:4rem}.approach-grid>div>p,.about-grid p{margin-top:2rem;font-size:1.1rem;line-height:1.75;opacity:.72}.approach ol{margin:0;padding:0;border-top:1px solid #ffffff44;list-style:none}.approach li{padding:1.5rem 0;border-bottom:1px solid #ffffff44}.approach li span{font-size:.58rem;font-weight:900;letter-spacing:.15em;color:var(--acid)}.approach h3{margin:1rem 0 0;font-size:1.7rem;letter-spacing:-.04em}.about{background:color-mix(in srgb,var(--ink) 92%,var(--primary))}.coach-mark{display:grid;overflow:hidden;aspect-ratio:1;place-items:center;border-radius:50%;background:var(--acid);color:var(--primary);font:900 clamp(5rem,12vw,11rem)/1 var(--display);letter-spacing:-.14em}
.results{background:var(--acid)}.results-grid{grid-template-columns:.6fr 1.4fr}.star{font-size:9rem;line-height:1;color:var(--primary)}.proof{margin-top:2rem;border-block:1px solid #0003}.proof p{display:grid;grid-template-columns:3rem 1fr;margin:0;padding:1.25rem 0;border-bottom:1px solid #0003;font-size:1.1rem;font-weight:700}.proof p:last-child{border:0}.proof span{font-size:.7rem;opacity:.45}.quote blockquote{max-width:75rem;margin:2.5rem 0 0;font-size:clamp(2.8rem,6vw,5.7rem);line-height:.94;letter-spacing:-.055em}.quote cite{display:block;margin-top:1.75rem;font-size:.65rem;font-style:normal;letter-spacing:.16em;text-transform:uppercase}
.questions-grid details{padding:1.5rem 0;border-block:1px solid #0003}.questions-grid summary{display:flex;justify-content:space-between;gap:1rem;font-size:1.15rem;font-weight:700;cursor:pointer;list-style:none}.questions-grid details p{margin-top:1.25rem;line-height:1.7;opacity:.65}.final{min-height:36rem;background:var(--primary);color:var(--paper)}.final h2{margin-top:3.5rem;font-size:clamp(5rem,12vw,12rem)}.final p{max-width:38rem;font-size:1.25rem;line-height:1.55}footer{display:flex;flex-wrap:wrap;justify-content:space-between;gap:1rem;padding:2.5rem var(--gutter);background:var(--ink);color:var(--paper);font-size:.58rem;font-weight:900;letter-spacing:.14em;text-transform:uppercase}
@media(max-width:760px){nav{display:none}.hero.variant-image-signal{grid-template-columns:1fr}.hero-copy{min-height:40rem;padding:3rem 1.5rem}.hero h1,.hero.variant-dashboard h1{max-width:none;font-size:${headlineFit === "compact" ? "3.1rem" : "4.2rem"}}.hero-lower,.hero.variant-dashboard .hero-lower,.programme-head,.approach-grid,.about-grid,.results-grid,.questions-grid,.week-shell{max-width:none;grid-template-columns:1fr}.track{right:-22rem;top:-7rem}.hero-dashboard{position:relative;inset:auto;width:auto;margin:0 1.5rem 2rem}.hero-image{min-height:23rem}.section{padding:4rem 1.5rem}.section h2{font-size:3.3rem}.benefits{grid-template-columns:1fr}.benefits article{min-height:auto;border-right:0;border-bottom:1px solid #0003}.benefits strong{margin-top:1.5rem}.week-intro{border-right:0;border-bottom:1px solid #0003}.star{font-size:6rem}.final h2{font-size:5rem}}
</style></head><body><header><div class="brand"><span class="mark">${h((props.brief.businessName || "M").charAt(0))}↗</span>${h(props.brief.businessName)}</div><nav>${ordered.includes("services") ? '<a href="#programme">Programme</a>' : ""}${ordered.includes("schedule") ? '<a href="#week">Your week</a>' : ""}${ordered.includes("approach") ? '<a href="#approach">How it works</a>' : ""}</nav></header><main><section class="hero variant-${h(heroVariant)}" data-hero="${h(heroVariant)}"><div class="hero-copy"><div class="hero-top"><span>${h(props.brief.mainService)}</span><span>${h(props.brief.deliveryMode || "Online")} ↗</span></div><div><h1>${h(props.copy.headline)}</h1><div class="hero-lower"><p>${h(props.copy.subheadline)}</p>${action}</div></div><small>01 / MAKE IT YOURS</small></div>${heroVisual}</section>${ordered.map(moduleHtml).join("")}</main><footer><b>${h(props.brief.businessName)}</b><span>${h(props.brief.deliveryMode || props.brief.location)}</span><span>${h(props.copy.button)}</span></footer></body></html>`;
}
